on:
  pull_request:
    branches:
      - oci-chart

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: Context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_DEMO_TOKEN }}
        url: ${{ secrets.OKTETO_DEMO_URL }}

    - name: Deploy preview environment
      uses: okteto/deploy-preview@latest
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: movies-api-pr-${{ github.event.number }}
        scope: global
        timeout: 15m